### ISSUE TITLE
Example program parsing_into_a_class.cpp fails to execute correctly under MSVC.

### ISSUE THREAD

**Issue by cfmileto** [boostorg/parser#206]
The example program parsing_into_a_class.cpp compiles correctly under MSVC but does not execute correctly.

I was able to get the first parser (string_uint_unit) in the example to execute correctly if I enclosed it inside the string_view directive.

Also, the second parser (uint_string) does not execute correctly.

**Comment by tzlaine** [comment]
Thanks for reporting this.  Could you tell me which MSVC you're using, which C++ build more you're compiling with, whether you enable `/Zc:__cplusplus`, and how the execution fails?

**Comment by cfmileto** [comment]
In response to the programs request for input ("Enter a string followed by two unsigned integers. "), I entered the string “abc 123 654”. The program then terminates with an unhandled exception “Microsoft C++ exception: std::out_of_range at memory location 0x00000071F48FE0E0.” from the include file xstring (in C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xstring).

 

I tried enabling “/Zc:__cplusplus” but got the same result.

 

Below is a copy of info from the Visual Studio help page that I think identifies the C++ compiler build:

 

“Microsoft Visual Studio Community 2022

Version 17.11.5

VisualStudio.17.Release/17.11.5+35327.3

Microsoft .NET Framework

Version 4.8.09037

 

Installed Version: Community

 

Visual C++ 2022   00482-90000-00000-AA095

Microsoft Visual C++ 2022

 

ASP.NET and Web Tools   17.11.231.19466

ASP.NET and Web Tools

 

Azure App Service Tools v3.0.0   17.11.231.19466

Azure App Service Tools v3.0.0

 

C# Tools   4.11.0-3.24460.3+5649376e0e5f5db3743a94a62b073f2cce4be5d9

C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

 

GitHub Copilot   0.2.1657.32929

GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

 

Microsoft JVM Debugger   1.0

Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

 

NuGet Package Manager   6.11.1

NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

 

Test Adapter for Boost.Test   1.0

Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

 

Visual Basic Tools   4.11.0-3.24460.3+5649376e0e5f5db3743a94a62b073f2cce4be5d9

Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

 

Visual C++ for Cross Platform Mobile Development (Android)   15.0.35103.136

Visual C++ for Cross Platform Mobile Development (Android)

 

Visual Studio IntelliCode   2.2

AI-assisted development for Visual Studio.”

 

Please let me know if you need additional info. Thank you for your assistance.

 

Chris Mileto

**Comment by tzlaine** [comment]
Thanks for the extra info!  Things are definitely supposed to work for that version of MSVC.  It would also help to know what it does -- that is, how exactly is it behaving badly?  Like, could you just run it and show the shell input+output when you do?

**Comment by tzlaine** [comment]
Why I ask is that it seems the second parser is just wrong.  I wrote it as `constexpr auto uint_string = bp::uint_ >> bp::char_ >> bp::char_`, but it should probably be `constexpr auto uint_string = bp::uint_ >> +bp::char_`.  I just want to make sure that this is the actual problem you're seeing, and not something else (since there could be two problems!).

**Comment by tzlaine** [comment]
One more thing -- the title says "fails to execute correctly under MSVC".  Does this mean that it works correctly on Clang or GCC, or were you just listing the compiler to add more info?

**Comment by tzlaine** [comment]
Ok, I pushed a commit that I think is the fix.  It's not MSVC-specific.  Please re-open if this did not fix the failure you saw.

**Comment by cfmileto** [comment]
Sorry, for my late response, I have been out of pocket for a while.

 

With respect to the example program parsing_into_a_class.cpp, the problem I experienced was with the first parser in the example; namely

 

constexpr auto string_uint_uint = bp::lexeme[+(bp::char_ - ' ')] >> bp::uint_ >> bp::uint_;

 

I also compiled and executed the example under GCC (linking to the same Boost library compiled by Microsoft) and got a similar failure as compiling and executing under Microsoft.

 

If I wrap the parser in the string_view directive (as follows

 

constexpr auto string_uint_uint = bp::string_view[bp::lexeme[+(bp::char_ - ' ')] >> bp::uint_ >> bp::uint_];

 

then the program executes correctly.

 

The Boost library (1.87.beta) was successfully built using the standard command b2 toolset=msvc –build-type=complete stage.

 

The following image is the Windows 10 shell generated from Microsoft’s Visual Studio IDE when the example program is invoked and input is entered:

 



 

 

The following image is produced from the Visual Studio IDE when the example program fails to continue execution:

 



 

Thanks for your assistance.

**Comment by tzlaine** [comment]
I'm able to get the program to compile and execute correctly on GCC using several different versions of GCC.  I still don't know exactly what problem you're seeing; could you share a terminal screenshot (or just copy/paste the session) that shows the misbehavior?

**Comment by cfmileto** [comment]
I sent you two screen shots in my previous email of the misbehavior, maybe they didn’t come through.

 

When I run the example program via the Microsoft Visual Studio IDE, the following Windows 10 command shell opens up with the prompt “Enter a string followed by two unsigned integers.”, when I enter the string “abc 123 456” the program hangs with an exception that can be seen in the second screen shot below in a window of the IDE.

 

First screen shot of Windows command shell:

 



 

Second screen shot of IDE:

**Comment by tzlaine** [comment]
Ah!  I get you now.  Yeah, but that's because you told it to do that. :)  The example takes the first thing parsed, a `std::string`, and uses it and the next two things parsed (both integers) to construct a new `std::string`.

In other words, to told the program to please construct a string like `s2`:

```c++
std::string s1("abc");

std::string s2(s1, 123, 123);
```

And it faithfully followed your commands, but those indices are out of bounds.  If you wrote `abc 1 2` it would have worked fine, and constructed a string equal to `"bc"`.

**Comment by tzlaine** [comment]
Oh, and BTW, I *still* can't see any screenshots, in the emails I got, or here.  Not sure why.  Thanks for following up, though.

**Comment by cfmileto** [comment]
Ah! Works just like you said!

 

As a novice to your library, it wasn’t intuitively obvious to me that the parser was matching the parsed tokens to a class constructor.

 

I had assumed that the parser looked at the type of the variable to receive the parse in this case “string_from_parse” defined as std::string and would subsequently output the first token (a string) as is and then convert and append the uints to one instance of a string.

 

Thanks so much for bearing with me. I look forward to using your library. I have used Spirit X3 in the past and have also encountered the same attribute generation problems that you mentioned you encountered with it that may have prompted you to develop your library.

**Comment by tzlaine** [comment]
Sure thing!  The generation of a std::string from std::string, int, int, was actually the point of that particular example.  It's showing how Boost.Parser will try to find a ctor that matches some sequence of attributes.  That's not 100% clear from the example code, but the part of the docs where the example code is quote makes it clearer.
